export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'

//CHANNEL ACTION TYPES
export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL'

export const SET_PRIVATE_CHANNEL = 'SET_PRIVATE_CHANNEL'

export const MESS_COUNT = 'MESS_COUNT'

export const MESS_ZERO = 'MESS_ZERO'

export const SET_USER_POSTS = 'SET_USER_POSTS'

export const SET_COLORS = 'SET_COLORS'

export const SET_KEY = 'SET_KEY'

export const SET_STAR_CHANNEL = 'SET_STAR_CHANNEL'

export const SET_CANCEL_CHANNEL_STAR = 'SET_CANСEL_CHANNEL_STAR'

export const SET_USERS_COLORS = 'SET_USERS_COLORS'

export const SET_AVATAR = 'SET_AVATAR'

export const SET_USER_POSTS_AVATAR = 'SET_USER_POSTS_AVATAR'